### PR TITLE
Working on fixing ISO8601 parsing 

### PR DESCRIPTION
**Pull request by ciozi137**
- optional fractional seconds
- optional timezone
- Time without date
- add test string files from https://ijmacd.github.io/rfc3339-iso8601/

@francois-normandin this version is parsing more variants but is probably still incomplete

### CODE REVIEW

**Comment by ciozi137** [comment]
@francois-normandin Change summary:

### ISO8601 DateString to Timestamp.vi: UTC Date-Time Case:
image

### ISO8601 DateString to Timestamp.vi: ISO Time Case:
image

### Timestamp to ISO8601 Time.vi
- a new method called by DateTime.ISO8601.lvclass:toString.vi

image

### Test Files
- add test files from [RFC 3339 vs ISO 8601](https://ijmacd.github.io/rfc3339-iso8601/)

image

### Test ISO8601 DateTime Strings.vi:
image

**Comment by francois-normandin** [comment]
Thanks @ciozi137 !
I'll probably review this in a couple weeks, so don't be alarmed by my silence in the coming days...

**Comment by ciozi137** [comment]
hey @francois-normandin no problem - understood!

**Comment by francois-normandin** [comment]
There seems to be cases where the conversion trims the milliseconds.
Not yet sure why, but I cannot merge the pull request as is. I`ll try to isolate the issue (probably in the Formatter class) and document what has changed.
image

**Comment by francois-normandin** [comment]
Should be a simple fix. We need to remove the comma/dot in the fractional second output
image

**Comment by francois-normandin** [comment]
That fixes it in all cases.

image

**Comment by francois-normandin** [comment]
Thanks for the test vectors. I'll push a change to add the expected validity in the file, so we can have a global greenlight when all is good. I'd like to keep those files out of the main project, and add Caraya tests for the report, but it will need to be in a separate project file to keep Caraya out of the built package.

image

**Comment by francois-normandin** [comment]
If the timezone is optional, we will have to support it in the conversion. At the moment, an optional timezone results in an invalid timestamp. In the absence of a timezone, we'll need to resolve to "local time" and thus use a strategy like this:

image

**Comment by francois-normandin** [comment]
I also found another issue with Local UTC Offset. When I use this LV timestamp: 20:00:00,000 2024-03-09, I get a differential of +16:00 hours, instead of -08:00, so the UTC offset is invalid (out of range). Therefore, this test does not pass for about half the vectors.
image

**Comment by francois-normandin** [comment]
I'll separate the tests into a lvproj and merge your branch into a dev branch. We can pick it up from there.

**Comment by francois-normandin** [comment]
I migrated the test vectors to new files, to test VALID, INVALID and AMBIGUOUS in Strict/non-strict contexts

image

**Comment by francois-normandin** [comment]
@ciozi137 Your changes have been carried into the iso8601_Tests branch.

**Pull request merged**
